# Generated by Django 5.0.7 on 2024-07-21 11:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=70)),
                ('phone_no', models.CharField(max_length=70)),
            ],
            options={
                'unique_together': {('contact_name', 'city', 'state', 'email_address', 'address', 'phone_no')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('order_status', 'Order status'), ('post_update', 'Post update'), ('new_subscription', 'New subscrition'), ('product_update', 'Product update'), ('stock_related', 'stock related')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('shipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.shipment')),
                ('payment_method', models.CharField(max_length=30)),
            ],
            bases=('order.shipment',),
        ),
        migrations.CreateModel(
            name='ShipmentInfo',
            fields=[
                ('shipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.shipment')),
                ('tracking_info', models.CharField(max_length=100)),
            ],
            bases=('order.shipment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_status', models.CharField(default='pending', max_length=30)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart')),
            ],
        ),
    ]
