# Generated by Django 5.0.7 on 2024-08-06 17:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('product', '0004_category_date_added_subcategory_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='order.billinginfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='order.shipmentinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('aborted', 'Aborted'), ('completed', 'Completed'), ('suspended', 'Suspended')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='phone_no',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Field must contain only numbers.', regex='^[0-9]{10}$')]),
        ),
        migrations.CreateModel(
            name='SingleProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_status', models.CharField(default='pending', max_length=30)),
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_product_order', to='order.billinginfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_product_order', to='order.shipmentinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
