# Generated by Django 5.0.7 on 2024-08-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('order', '0003_remove_order_billing_id_remove_order_shipment_id_and_more'),
        ('user', '0005_remove_metrics_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproductorder',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='user',
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
