# Generated by Django 5.0.7 on 2024-08-28 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartorder_date_remove_cartorder_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='order_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
