# Generated by Django 5.0 on 2025-07-11 18:04

import django.contrib.postgres.fields
import django.core.validators
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[shared.validators.check_vulgarity])),
                ('description', models.TextField(validators=[shared.validators.check_vulgarity])),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(20)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('tags', models.JSONField(default=dict)),
                ('tag_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True, validators=[shared.validators.check_vulgarity, django.core.validators.MinLengthValidator(1)])),
                ('rating', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('popularity_ratio', models.DecimalField(decimal_places=1, default=0.1, max_digits=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('three_day_threshold', models.PositiveIntegerField()),
                ('fourteen_day_threshold', models.PositiveIntegerField()),
                ('twenty_one_day_threshold', models.PositiveIntegerField()),
                ('wishlist_threshold', models.PositiveIntegerField(default=500)),
                ('conversion_rate_threshold', models.PositiveIntegerField(default=0.6)),
                ('rating_threshold', models.PositiveIntegerField(default=0.7)),
            ],
            options={
                'ordering': ['-popularity_ratio'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorySearchWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TokenToSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('subcategories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
            ],
        ),
    ]
