# Generated by Django 5.0 on 2025-01-21 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_tokentosubcategory_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='conversion_rate_threshold',
            field=models.PositiveIntegerField(default=0.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='fourteen_day_threshold',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='popularity_ratio',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=2, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='rating_threshold',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='three_day_threshold',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='twenty_one_day_threshold',
            field=models.PositiveIntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='wishlist_threshold',
            field=models.PositiveIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
