# Generated by Django 5.0 on 2025-02-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_date_added_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-popularity_ratio']},
        ),
    ]
