# Generated by Django 5.0 on 2025-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='conversion_rate_threshold',
            field=models.PositiveIntegerField(default=0.6),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rating_threshold',
            field=models.PositiveIntegerField(default=0.7),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='wishlist_threshold',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
