# Generated by Django 5.0 on 2025-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_subcategory_conversion_rate_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
