# Generated by Django 5.0 on 2025-05-07 12:05

import django.contrib.postgres.fields
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[shared.validators.check_vulgarity]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
