# Generated by Django 5.0 on 2025-05-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='at_least_one_parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dummy',
        ),
    ]
