# Generated by Django 5.0 on 2025-01-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_replies_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
