# Generated by Django 5.0 on 2025-05-01 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_comment_at_least_one_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post__isnull', True), ('parent_comment__isnull', False)), models.Q(('post__isnull', False), ('parent_comment__isnull', True)), _connector='OR'), name='at_least_one_parent'),
        ),
    ]
