# Generated by Django 5.0.7 on 2024-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_history_cart_alter_history_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='current_stoke',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
    ]
