# Generated by Django 5.0.7 on 2024-08-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_metrics_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
