# Generated by Django 5.0.7 on 2024-09-08 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
