# Generated by Django 5.0.7 on 2024-09-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_wishlist_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
