# Generated by Django 5.0.7 on 2024-08-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
    ]
