# Generated by Django 5.0 on 2025-01-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='date',
            new_name='created_at',
        ),
    ]
