# Generated by Django 5.0 on 2025-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_timestamp_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'inactive')], default='active'),
            preserve_default=False,
        ),
    ]
