# Generated by Django 5.0 on 2025-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'inactive')], default='active'),
        ),
    ]
