# Generated by Django 5.0.7 on 2024-08-09 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_date_added_subcategory_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(related_name='reviewed_product', to='product.review'),
        ),
    ]
