# Generated by Django 5.0.7 on 2024-07-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('product', '0004_category_date_added_subcategory_date_added'),
        ('user', '0002_wishlist_modified_at_alter_wishlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='product.product'),
        ),
    ]
