# Generated by Django 5.0 on 2025-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_metrics_customer_remove_metrics_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='customer'),
            preserve_default=False,
        ),
    ]
