# Generated by Django 4.2.5 on 2023-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='populatiry',
            new_name='popularity',
        ),
    ]
