# Generated by Django 5.0 on 2025-07-11 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=70)),
                ('tracking_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebuss_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('payment_gateway', models.CharField(choices=[('chapa', 'Chapa')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('last_verification_time', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('trx_ref', models.CharField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('aborted', 'Aborted'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorder_in', to='cart.cart')),
            ],
        ),
    ]
