# Generated by Django 5.0 on 2025-07-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorders_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentinfo',
            unique_together={('contact_name', 'city', 'state', 'address')},
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='order.shipmentinfo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.cartorder'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_ref'], name='order_trans_tx_ref_63b225_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='order_trans_status_022774_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_gateway'], name='order_trans_payment_81d689_idx'),
        ),
    ]
