# Generated by Django 5.0.7 on 2024-07-21 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.billinginfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.shipmentinfo'),
        ),
    ]
