# Generated by Django 5.0 on 2025-07-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentinfo',
            name='tracking_info',
        ),
    ]
