# Generated by Django 5.0 on 2025-07-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_shipmentinfo_tracking_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='trx_ref',
            new_name='tx_ref',
        ),
    ]
