# Generated by Django 5.0 on 2025-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_trx_ref_cartorder_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('chapa', 'Chapa')], default='chapa', max_length=20),
        ),
    ]
