# Generated by Django 5.0.7 on 2024-08-26 17:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_product'),
        ('order', '0004_remove_singleproductorder_billing_and_more'),
        ('product', '0005_product_rating_product_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='order.billinginfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='order.shipmentinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='singleproduct_orders_in', to='order.billinginfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='order_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='singleproduct_orders_in', to='order.shipmentinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleproductorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='singleproduct_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorders_in', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='singleproductorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productorders_in', to='product.product'),
        ),
    ]
