# Generated by Django 5.0.7 on 2024-08-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartorder_billing_cartorder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='order_status',
        ),
    ]
