# Generated by Django 5.0 on 2025-01-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cartorder_date_cartorder_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='singleproductorder',
            old_name='date',
            new_name='created_at',
        ),
    ]
