# Generated by Django 5.0 on 2025-03-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_timestamp_cart_created_at_and_more'),
        ('order', '0008_rename_date_cartorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorders_in', to='cart.cartdata'),
        ),
    ]
