# Generated by Django 5.0 on 2025-04-23 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_status'),
        ('order', '0009_alter_cartorder_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorder_in', to='cart.cartdata'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorders_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
