# Generated by Django 5.0 on 2025-04-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_status'),
        ('order', '0010_alter_cartorder_cart_alter_cartorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartorder_in', to='cart.cart'),
        ),
    ]
