# Generated by Django 5.0 on 2025-06-10 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_cartorder_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('gateway', models.CharField(choices=[('chapa', 'Chapa')])),
                ('trx_ref', models.CharField(unique=True)),
                ('ref_id', models.CharField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('aborted', 'Aborted'), ('success', 'Success'), ('failed', 'Failed')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ref_id', 'gateway')},
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
